# Generated by Django 5.2.17 on 2026-08-26 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('device_name', models.CharField(max_length=160)),
                ('location_name', models.CharField(blank=True, max_length=160)),
                ('platform', models.CharField(blank=True, max_length=80)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending_enrollment', 'Awaiting enrollment'), ('enrolled', 'Enrolled'), ('revoked', 'Revoked')], default='pending_enrollment', max_length=32)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=32)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('sync_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=80, unique=True)),
                ('client_secret_hash', models.CharField(max_length=256)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='sync_core.device')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='sync_core.device')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='sync_core.facility')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='sync_core.facility'),
        ),
        migrations.AddField(
            model_name='facility',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='sync_core.institution'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_facility_code_per_institution'),
        ),
    ]
