# Generated by Django 5.2.17 on 2026-08-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDataRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='sync_core.facility')),
                ('source_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_records', to='sync_core.device')),
            ],
            options={
                'ordering': ['-source_updated_at', '-received_at', 'record_id'],
                'indexes': [models.Index(fields=['facility', 'table_name', 'deleted'], name='facility_table_live_idx')],
                'constraints': [models.UniqueConstraint(fields=('facility', 'table_name', 'record_id'), name='unique_facility_table_record')],
            },
        ),
    ]
