# Generated by Django 5.2.17 on 2026-08-26 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0002_facilitydatarecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitySyncEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_public_id', models.CharField(max_length=160)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_entities', to='sync_core.facility')),
                ('source_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_entities', to='sync_core.device')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('facility', 'entity_type', 'entity_public_id'), name='unique_facility_sync_entity')],
            },
        ),
        migrations.CreateModel(
            name='FacilitySyncEvent',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_public_id', models.CharField(max_length=160)),
                ('operation', models.CharField(max_length=16)),
                ('base_version', models.PositiveBigIntegerField()),
                ('entity_version', models.PositiveBigIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='sync_core.facility')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_events', to='sync_core.device')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['facility', 'sequence'], name='facility_sync_cursor_idx')],
            },
        ),
    ]
