# Generated by Django 5.2.17 on 2026-08-26 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0004_project_sync_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeFileObject',
            fields=[
                ('oid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(default='application/octet-stream', max_length=160)),
                ('storage_path', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LargeFileReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_public_id', models.CharField(max_length=160)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_file_references', to='sync_core.facility')),
                ('file_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='references', to='sync_core.largefileobject')),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='large_file_references', to='sync_core.device')),
            ],
            options={
                'indexes': [models.Index(fields=['facility', 'entity_type', 'entity_public_id'], name='facility_lfs_entity_idx')],
                'constraints': [models.UniqueConstraint(fields=('facility', 'file_object', 'entity_type', 'entity_public_id'), name='unique_facility_large_file_reference')],
            },
        ),
    ]
