# Generated by Django 5.2.17 on 2026-10-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0005_largefileobject_largefilereference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitysyncevent',
            name='source_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_events', to='sync_core.device'),
        ),
        migrations.CreateModel(
            name='FacilitySyncConflict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_public_id', models.CharField(max_length=160)),
                ('operation', models.CharField(max_length=16)),
                ('base_version', models.PositiveBigIntegerField()),
                ('incoming_payload', models.JSONField(default=dict)),
                ('canonical_version', models.PositiveBigIntegerField()),
                ('canonical_payload', models.JSONField(default=dict)),
                ('canonical_deleted', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Needs review'), ('resolved', 'Resolved'), ('auto_resolved', 'Settled automatically')], default='open', max_length=16)),
                ('resolution', models.CharField(blank=True, choices=[('kept_server', 'Kept the server version'), ('applied_device', 'Applied the device version'), ('device_resent', 'Device re-sent its change on top'), ('older_credential_ignored', 'Older password change ignored')], max_length=32)),
                ('resolution_event_id', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sync_core.device')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_conflicts', to='sync_core.device')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to='sync_core.facility')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'status'], name='facility_conflict_status_idx'), models.Index(fields=['facility', 'entity_type', 'entity_public_id'], name='facility_conflict_entity_idx')],
            },
        ),
    ]
