# Generated by Django 5.2.17 on 2026-10-06 15:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0006_sync_conflicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.PositiveSmallIntegerField(db_index=True)),
                ('level_name', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('client_ip', models.CharField(blank=True, max_length=64)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('traceback', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='sync_core.device')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='sync_core.facility')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['level', '-created_at'], name='system_log_level_idx')],
            },
        ),
    ]
