# Generated by Django 5.2.17 on 2026-10-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_core', '0007_system_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_sync_host',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
