from dataclasses import dataclass


@dataclass(frozen=True)
class DataTable:
	name: str
	label: str
	group: str


DATA_TABLES = (
	DataTable("users", "Users", "Identity & access"),
	DataTable("roles", "Roles", "Identity & access"),
	DataTable("permissions", "Permissions", "Identity & access"),
	DataTable("role_permissions", "Role permissions", "Identity & access"),
	DataTable("user_roles", "User roles", "Identity & access"),
	DataTable("user_permissions", "User permissions", "Identity & access"),
	DataTable("patients_region", "Regions", "Patients"),
	DataTable("patients_occupationcategory", "Occupation categories", "Patients"),
	DataTable("patients_insurancetype", "Insurance types", "Patients"),
	DataTable("patients_insuranceprovider", "Insurance providers", "Patients"),
	DataTable("patients_patient", "Patients", "Patients"),
	DataTable("patients_insurance", "Patient insurance", "Patients"),
	DataTable("patient_oculo_medical_history", "Oculo-medical history", "Patients"),
	DataTable("patient_medical_conditions", "Patient medical conditions", "Patients"),
	DataTable("patient_ocular_conditions", "Patient ocular conditions", "Patients"),
	DataTable("patient_family_medical_conditions", "Family medical conditions", "Patients"),
	DataTable("patient_family_ocular_conditions", "Family ocular conditions", "Patients"),
	DataTable("appointments", "Appointments", "Appointments"),
	DataTable("appointment_types", "Appointment types", "Appointments"),
	DataTable("clinic_schedule", "Clinic schedule", "Appointments"),
	DataTable("consultation_versions", "Consultations", "Clinical records"),
	DataTable("consultation_chief_complaints", "Chief complaints", "Clinical records"),
	DataTable("consultation_odq_observations", "ODQ observations", "Clinical records"),
	DataTable("consultation_visual_acuity", "Visual acuity", "Clinical records"),
	DataTable("consultation_external_observations", "External observations", "Clinical records"),
	DataTable("consultation_internal_observations", "Internal observations", "Clinical records"),
	DataTable("consultation_refractions", "Refraction", "Clinical records"),
	DataTable("consultation_objective_refraction", "Objective refraction", "Clinical records"),
	DataTable("consultation_subjective_refraction", "Subjective refraction", "Clinical records"),
	DataTable("consultation_cycloplegic_refraction", "Cycloplegic refraction", "Clinical records"),
	DataTable("diagnosis_codes", "Diagnosis codes", "Clinical records"),
	DataTable("consultation_diagnoses", "Diagnoses", "Clinical records"),
	DataTable("consultation_diagnosis_entries", "Diagnosis entries", "Clinical records"),
	DataTable("consultation_management_plans", "Management plans", "Clinical records"),
	DataTable("consultation_medication_instructions", "Medication instructions", "Clinical records"),
	DataTable("consultation_grades", "Consultation grades", "Clinical records"),
	DataTable("consultation_section_grades", "Section grades", "Clinical records"),
	DataTable("case_management_guides", "Case management guides", "Clinical records"),
	DataTable("case_management_guide_items", "Case management guide items", "Clinical records"),
	DataTable("consultation_extra_tests", "Extra tests", "Labs"),
	DataTable("consultation_extra_test_requests", "Lab requests", "Labs"),
	DataTable("test_catalog", "Test catalog", "Labs"),
	DataTable("pharmacy_orders", "Pharmacy orders", "Pharmacy"),
	DataTable("pharmacy_order_items", "Pharmacy order items", "Pharmacy"),
	DataTable("inventory_categories", "Inventory categories", "Inventory"),
	DataTable("inventory_items", "Inventory items", "Inventory"),
	DataTable("inventory_movements", "Inventory movements", "Inventory"),
	DataTable("payments", "Payments", "Finance"),
	DataTable("service_prices", "Service prices", "Finance"),
	DataTable("devices", "Local devices", "Operations"),
	DataTable("activity_logs", "Activity logs", "Operations"),
	DataTable("notifications", "Notifications", "Operations"),
	DataTable("messages", "Messages", "Operations"),
	DataTable("app_settings", "Application settings", "Operations"),
	DataTable("institutions", "Institutions", "Operations"),
	DataTable("examinations_condition", "Conditions", "Reference data"),
	DataTable("examinations_internalexternalconditionmaingroup", "Observation groups", "Reference data"),
	DataTable("examinations_internalexternalconditionsubstructure", "Observation substructures", "Reference data"),
	DataTable("examinations_internalexternalcondition", "Observation conditions", "Reference data"),
	DataTable("id_types", "ID types", "Reference data"),
	DataTable("genders", "Genders", "Reference data"),
	DataTable("patient_types", "Patient types", "Reference data"),
	DataTable("clinics", "Clinics", "Reference data"),
	DataTable("tonometry_methods", "Tonometry methods", "Reference data"),
	DataTable("visual_acuity_chart_options", "VA chart options", "Reference data"),
	DataTable("visual_acuity_prescription_types", "VA prescription types", "Reference data"),
	DataTable("last_eye_exam_options", "Last eye exam options", "Reference data"),
)

DATA_TABLE_MAP = {table.name: table for table in DATA_TABLES}
SYNC_ENTITY_TABLE_MAP = {
	"activity_log": "activity_logs",
	"appointment": "appointments",
	"consultation_version": "consultation_versions",
	"finance_payment": "payments",
	"inventory_category": "inventory_categories",
	"inventory_item": "inventory_items",
	"inventory_movement": "inventory_movements",
	"patient": "patients_patient",
	"pharmacy_order": "pharmacy_orders",
	"user": "users",
}

SYNC_ENTITY_PAYLOAD_KEYS = {
	"appointment": "appointment",
	"consultation_version": "version",
	"finance_payment": "payment",
	"inventory_category": "category",
	"inventory_item": "item",
	"inventory_movement": "movement",
	"patient": "patient",
	"pharmacy_order": "order",
	"user": "user",
}
